:sparkles: return optimal text and line arguments
ckjellson/textalloc pull request #20
Opened 2024-05-06 20:39 UTC by ThomasParistech

It's sometimes useful to be able to store the optimal text boxes positions.

It won't break previous usage since nothing was returned.

2024-05-09 10:40 UTC, ckjellson commented on src/textalloc/__init__.py
> +        result_line (List[Union[Optional[Tuple[float, float], Tuple[float, float]]]]): List of optimal (x,y) arguments to use when calling plt.plot to draw the line.
Change to:
    Returns:
        result_text_xy (List[Optional[Tuple[float, float]]]): List of resulting (x,y) positions for text labels used in the plt.text call.
        result_lines (List[Union[Optional[Tuple[float, float], Tuple[float, float]]]]): List of resulting (x,y) pairs used in the plt.plot call for drawing lines.

2024-05-09 10:47 UTC, ckjellson requested changes
Very nice, thank you! It hurts my eyes a bit as a math-guy to see the word "optimal" here since the method will never be optimal 😅, I suggested some changes in the docs, and it would also be great if you could add something about it in the README after the parameters section, along the lines of:
"The allocate call returns a tuple containing the resulting positions used to plot the text labels and the connecting label lines"

Fix this and maybe change the commit-message as well to "return resulting text and line positions" and I will merge and update the pypi package!

2024-05-12 08:00 UTC, ThomasParistech commented
I've applied your suggestion

You're right for the optimal adjective :smile:

2024-05-12 08:04 UTC, merged

2024-05-12 08:09 UTC, ckjellson commented
Merged and updated pypi package